export const SET_USER = '@User/SET_USER'

export const FETCH_CURRENT_USER = '@User/FETCH_CURRENT_USER'
export const FETCH_CURRENT_CREDENTIALS = '@User/FETCH_CURRENT_CREDENTIALS'

export const FETCH_USER_LOGIN = '@User/FETCH_USER_LOGIN'
export const FETCH_NEW_PASSWORD = '@User/FETCH_NEW_PASSWORD'
export const FETCH_USER_LOGOUT = '@User/FETCH_USER_LOGOUT'
